language: php

matrix:
    include:
        - php: 7.0
          env: SYMFONY_VERSION="~3.0" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: SYMFONY_VERSION="~3.1" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: SYMFONY_VERSION="~3.2" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: SYMFONY_VERSION="~3.3" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: SYMFONY_VERSION="~3.0" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: SYMFONY_VERSION="~3.1" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: SYMFONY_VERSION="~3.2" COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: SYMFONY_VERSION="~3.3" COMPOSER_FLAGS="--prefer-stable"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - 'if [ "$SYMFONY_VERSION" != "" ]; then sed -i "s/\"symfony\/\([^\"]*\)\": \"[^\"]*\"/\"symfony\/\1\": \"$SYMFONY_VERSION\"/g" composer.json; fi'

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN=cacacf270d34ee54c9923ce4fd962f73eda95c26622e5980b6af5d182f169cf6 ./vendor/bin/test-reporter
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: cacacf270d34ee54c9923ce4fd962f73eda95c26622e5980b6af5d182f169cf6

after_success:
    - php vendor/bin/coveralls -v
